### ISSUE TITLE
npm install cheerio -> npm ERR! 404 Not Found: @types/node@6.0.46 

### ISSUE THREAD

**Issue by thepianist2** [cheeriojs/cheerio#1035]
Hi, i want install cheerio, but show this error:

I have tried deleted cache and not solved.
```
npm install cheerio
npm ERR! code E404
npm ERR! 404 Not Found: @types/node@6.0.46
```

```
node -v
v8.0.0
```

```
npm -v 
5.0.3
```

And the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\fag74272\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@types/node@6.0.46' ]
2 info using npm@5.0.3
3 info using node@v8.0.0
4 verbose npm-session 607a4151d366dc1c
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 http://intersinopia:4873/@types%2fnode 47ms
8 silly fetchPackageMetaData error for @types/node@6.0.46 404 Not Found: @types/node@6.0.46
9 verbose stack Error: 404 Not Found: @types/node@6.0.46
9 verbose stack     at fetch.then.res (C:\Users\fag74272\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
9 verbose stack     at tryCatcher (C:\Users\fag74272\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\fag74272\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Users\fag74272\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Users\fag74272\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Users\fag74272\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Users\fag74272\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Users\fag74272\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Users\fag74272\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:800:20)
9 verbose stack     at tryOnImmediate (timers.js:762:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
10 verbose cwd C:\front\node_embed_laboratory
11 verbose Windows_NT 6.1.7601
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fag74272\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@types/node@6.0.46"
13 verbose node v8.0.0
14 verbose npm  v5.0.3
15 error code E404
16 error 404 Not Found: @types/node@6.0.46
17 verbose exit [ 1, true ]
```

Any idea?

Thanks.

**Comment by luanmuniz** [comment]
I could not reproduce this. 
The problem seems to be here
```
http fetch GET 404 http://intersinopia:4873/@types%2fnode 47ms
```

It seems a DNS problem. Is `http://intersinopia:4873` an alias in your local?

**Comment by thepianist2** [comment]
Thank you very much,

Solved, the problem was solved removing the line:

`registry=http://intersinopia:4873/`

from the file .npmrc


Greetings.

**Comment by Jialufeng** [comment]
yarn add cheerio
