### ISSUE TITLE
Error: Cannot find module 'htmlparser2

### ISSUE THREAD

**Issue by lourdrivera123** [cheeriojs/cheerio#1067]
Hi there, does anyone get error like this as well ?

module.js:472
    throw err;
    ^

Error: Cannot find module 'htmlparser2'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zem/sites/pcsobot/node_modules/cheerio/lib/parse.js:4:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by lourdrivera123** [comment]
Closing issue, it was resolved after cleaning up node_modules and rerunning npm install.
