### ISSUE TITLE
$.xml is not a function ?

### ISSUE THREAD

**Issue by Belouccio** [cheeriojs/cheerio#1070]
Hello! I have a gulp task to generate a svg sprite.
gulp.task('svgSpriteBuild', function () {
    return gulp.src('src/svgs/*.svg')
    // minify svg
        .pipe(svgmin({
            js2svg: {
                pretty: true
            }
        }))
        // remove all fill and style declarations in out shapes
        .pipe(cheerio({

            run: function ($) {
                $('[fill]').removeAttr('fill');
                $('[style]').removeAttr('style');
            },
            parserOptions: { xmlMode: true }
        }))
        // cheerio plugin create unnecessary string '>', so replace it.
        .pipe(replace('&gt;', '>'))
        // build svg sprite
        .pipe(svgSprite({
                mode: "symbols",
                preview: false,
                selector: "icon-%f",
                svg: {
                    symbols: 'symbol_sprite.html'
                }
            }
        ))
        .pipe(gulp.dest('src/sptite/'));
});

gulp.task('default',
    gulp.series('svgSpriteBuild'));

After run gulp, I've got an error 
TypeError: $.xml is not a function
    at next (/home/developer/projects/lenta/news/node_modules/gulp-cheerio/lib/index.js:25:85)
    at DestroyableTransform._transform (/home/developer/projects/lenta/news/node_modules/gulp-cheerio/lib/index.js:19:9)
    at DestroyableTransform.Transform._read (/home/developer/projects/lenta/news/node_modules/gulp-cheerio/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/developer/projects/lenta/news/node_modules/gulp-cheerio/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/developer/projects/lenta/news/node_modules/gulp-cheerio/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/developer/projects/lenta/news/node_modules/gulp-cheerio/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/developer/projects/lenta/news/node_modules/gulp-cheerio/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Transform.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at Transform.emit (events.js:210:7)

Please tell how to fix it.

P.S. Sorry for my bad English)

**Comment by jugglinmike** [comment]
The error stack trace indicates that the exception originates in [the `gulp-cheerio` module](https://www.npmjs.com/package/gulp-cheerio). We do not maintain that package, so we're not in a good position to help with this particular problem. I recommend filing this issue on [that project's issue tracker](https://github.com/knpwrs/gulp-cheerio/issues).

Good luck!

**Comment by Belouccio** [comment]
Thank you!
