### ISSUE TITLE
AssertionError: expected { Object (options, _root, ...) } to have a length of 1 but got 0

### ISSUE THREAD

**Issue by ghost** [cheeriojs/cheerio#1115]
the test cases where running fine before updating the react and enzyme version but after updating i'm getting the below issue i have updated the cheerio version as well is this causing any issue 

AssertionError: expected { Object (options, _root, ...) } to have a length of 1 but got 0
      at Context.<anonymous> (C:/Users/Desktop/Project-Name/src/main/javascript/components/table/FileName.test.js:39:44)
      at callFn (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runnable.js:319:7)
      at Runner.runTest (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\Users\Desktop\Project-Name\node_modules\mocha\lib\runner.js:320:5)

**Comment by fb55** [comment]
Seems to be similar to https://github.com/airbnb/enzyme/issues/1421, but not enough context is provided.
