### ISSUE TITLE
Maximum call stack size exceeded, dom-serializer error

### ISSUE THREAD

**Issue by cmarrero01** [cheeriojs/cheerio#1127]
I found a big problem with dom-serializer dependencie, if you parse a long html, you will get a Maximum call size
```

RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Object.encodeXML (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/entities/lib/encode.js:58:6)
    at renderText (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:136:21)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:91:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)

```

**Comment by lesterjanpearson** [comment]
How many lines of code? I just did a 1000 line.

**Comment by fb55** [comment]
This happens because of recursive serialisation. It should only be an issue for insanely nested documents, which makes this not a priority right now.
