### ISSUE TITLE
Can't convert from CheerioElement to DOM Node

### ISSUE THREAD

**Issue by Jetmate** [cheeriojs/cheerio#1149]
I am trying to use Cheerio to manipulate the DOM.
```javascript
const $ = cheerio.load(text) // some html text
document.querySelector('#.some-destination').appendChild($('.some-class')[0])
```
**Expected behavior**
The CheerioElement returned by `$('.some-class')[0]` is accepted by `appendChild`

**Actual behavior**
```
Uncaught (in promise) TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at _callee$ (http://localhost:1234/dist/e274c430a0dc3f2fb76600b4d38b36b1.js:27902:81)
    at tryCatch (http://localhost:1234/dist/af6e5429b9288b8fd9e32d900260c725.js:79:1423)
    at Generator.invoke [as _invoke] (http://localhost:1234/dist/af6e5429b9288b8fd9e32d900260c725.js:79:2822)
    at Generator.t.(anonymous function) [as next] (http://localhost:1234/dist/af6e5429b9288b8fd9e32d900260c725.js:79:1671)
    at step (http://localhost:1234/dist/e274c430a0dc3f2fb76600b4d38b36b1.js:27944:191)
    at http://localhost:1234/dist/e274c430a0dc3f2fb76600b4d38b36b1.js:27944:361
    at <anonymous>
```
**Workaround**
```javascript
const $ = cheerio.load(text) // some html text
const node = new DOMParser().parseFromString(page$('.some-class').html(), 'text/html')
document.querySelector('#.some-destination').appendChild(node.body.firstChild)
```
This seems like it would be slower than supporting Cheerio to DOM natively, but I may be wrong.

**Comment by fb55** [comment]
Cheerio works on its own DOM implementation, which allows it to run in node. You probably want to use jQuery to have the same API operating on the browser's DOM itself.
