### ISSUE TITLE
TypeError: data.replace is not a function

### ISSUE THREAD

**Issue by evandrix** [cheeriojs/cheerio#1188]
trying to get `outerHTML`, i.e. semantically, `$("a").outerHTML()`, for the following:

`<a href="https://l.facebook.com/l.php?u=http%3A%2F%2Fwapo.st%2F2Hm0WZA&amp;h=ATNuSqfr8wRgMrsjpLAZrzfQxwVQgzegJ5I8BFvtLPYg3jVXluoqyjrVskaJ1pqg_RGsGLbtFWs8lkjUUxuSNz5fSvmNb1j1lcn6oofsB_JjZzg92p8" tabindex="-1" target="_blank" rel="noopener nofollow" data-lynx-mode="asynclazy"><div class="_6l- __c_"><div class="uiScaledImageContainer _6m5 fbStoryAttachmentImage" style="width:158px;height:158px;"><img class="scaledImageFitWidth img" src="https://external.fsin4-1.fna.fbcdn.net/safe_image.php?d=AQD_ZqUFVnrE1-Pj&amp;w=160&amp;h=160&amp;url=https%3A%2F%2Fwww.washingtonpost.com%2Frf%2Fimage_1484w%2F2010-2019%2FWashingtonPost%2F2015%2F03%2F31%2FForeign%2FImages%2FDV1997577.jpg%3Ft%3D20170517&amp;cfs=1&amp;upscale=1&amp;fallback=news_d_placeholder_publisher&amp;_nc_hash=AQCmeSxSfCAnZ9Jl" alt="" width="158" height="158"></div></div></a>`

using:

- `$(el).clone().wrap("<container/>").parent().html().trim();` fails
- `$(el).wrap("<container/>").parent().html().trim();` succeeds

stack trace:
```
TypeError: data.replace is not a function
	at Object.encodeXML (/usr/lib/node_modules/cheerio/node_modules/entities/lib/encode.js:58:6)
	at formatAttrs (/usr/lib/node_modules/cheerio/node_modules/dom-serializer/index.js:67:62)
	at renderTag (/usr/lib/node_modules/cheerio/node_modules/dom-serializer/index.js:132:17)
	at module.exports (/usr/lib/node_modules/cheerio/node_modules/dom-serializer/index.js:113:17)
	at render (/usr/lib/node_modules/cheerio/lib/static.js:75:10)
	at Object.exports.html (/usr/lib/node_modules/cheerio/lib/static.js:97:10)
	at initialize.exports.html (/usr/lib/node_modules/cheerio/lib/api/manipulation.js:385:14)
	...<redacted>...
	at <anonymous> Promise {
  <rejected> TypeError: data.replace is not a function
	at Object.encodeXML (/usr/lib/node_modules/cheerio/node_modules/entities/lib/encode.js:58:6)
	at formatAttrs (/usr/lib/node_modules/cheerio/node_modules/dom-serializer/index.js:67:62)
	at renderTag (/usr/lib/node_modules/cheerio/node_modules/dom-serializer/index.js:132:17)
	at module.exports (/usr/lib/node_modules/cheerio/node_modules/dom-serializer/index.js:113:17)
	at render (/usr/lib/node_modules/cheerio/lib/static.js:75:10)
	at Object.exports.html (/usr/lib/node_modules/cheerio/lib/static.js:97:10)
	at initialize.exports.html (/usr/lib/node_modules/cheerio/lib/api/manipulation.js:385:14)
	...<redacted>...
	at <anonymous> }
```

**Comment by fb55** [comment]
Looks like this has been fixed!

**Comment by therahl** [comment]
I am experiencing this error when using the latest release candidate (rc-5).  

Usage: `cheerio.load(MyFile, { normalizeWhitespace: true, xmlMode: true }).xml()`

Error:
```
TypeError: data.replace is not a function

      at Object.<anonymous> (../node_modules/entities/lib/encode.js:63:14)
      at renderText (../node_modules/dom-serializer/lib/index.js:198:27)
      at renderNode (../node_modules/dom-serializer/lib/index.js:134:20)
      at render (../node_modules/dom-serializer/lib/index.js:113:19)
      at renderTag (../node_modules/dom-serializer/lib/index.js:182:20)
      at renderNode (../node_modules/dom-serializer/lib/index.js:132:20)
      at render (../node_modules/dom-serializer/lib/index.js:113:19)
      at renderTag (../node_modules/dom-serializer/lib/index.js:182:20)
      at renderNode (../node_modules/dom-serializer/lib/index.js:132:20)
      at render (../node_modules/dom-serializer/lib/index.js:113:19)
      ```

**Comment by fb55** [comment]
@therahl Are you able to share the markup that triggers this behavior? Unfortunately that will be required to debug this issue.

**Comment by fb55** [comment]
Closing this as I cannot replicate the behavior.
