### ISSUE TITLE
cheerio.css on empty set throws, jQuery returns undefined.

### ISSUE THREAD

**Issue by fskreuz** [cheeriojs/cheerio#1208]
Reproduction:

```
$('selectorthatmatchesnothing').css('background-image')
```

- jQuery behavior: returns `undefined`
- cheerio behavior: Error thrown `Uncaught TypeError: Cannot read property 'attribs' of undefined`

```
Uncaught TypeError: Cannot read property 'attribs' of undefined
    at getCss (cheerio/lib/api/css.js:69:25)
    at initialize.exports.css (cheerio/lib/api/css.js:25:12)
```

I'd expect cheerio to at least return `undefined` just like jQuery.

**Comment by dksami** [comment]
Here is my contribution 
Just put this so that you can avoid getting undefined object for attribs
```
if(!cheerio.load(m)("img")[0]){
console.log("we got he undefined " +cheerio.load(m)("img")[0]);
					}else{
						var image = new Image(cheerio.load(m)("img")[0], ref.address);

						ref.emit("image", image);

					}
```
