### ISSUE TITLE
Cannot read property 'root' of undefined

### ISSUE THREAD

**Issue by winterchao** [cheeriojs/cheerio#1236]
Hi Cheerio Team
When i run cherio by nodejs I get some error
`var oldParent = node.root,
                         ^

TypeError: Cannot read property 'root' of undefined
    at Function.exports.update (C:\Users\Administrator\Desktop\pachong\node_modules\_cheerio@1.0.0-rc.2@cheerio\lib\parse.js:69:26)
    at module.exports (C:\Users\Administrator\Desktop\pachong\node_modules\_cheerio@1.0.0-rc.2@cheerio\lib\parse.js:19:11)
    at Function.exports.load (C:\Users\Administrator\Desktop\pachong\node_modules\_cheerio@1.0.0-rc.2@cheerio\lib\static.js:27:14)
    at handleDB (C:\Users\Administrator\Desktop\pachong\index.js:10:21)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\pachong\index.js:51:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
`

**Comment by fb55** [comment]
Not enough information to reproduce.
