### ISSUE TITLE
:matches not working  as expected

### ISSUE THREAD

**Issue by drdamour** [cheeriojs/cheerio#1292]
dom with

```
<td>commerce-ci-si1</td>
```

code of
```
$("td:matches(commerce.*)")
```

i expect to return the td node, but i actually get

```
[Mon Mar 18 2019 13:41:19 GMT-0600 (MDT)] ERROR TypeError: Cannot read property '0' of null
  at getName (/Users/chrisdamour/code/bwbot/node_modules/css-what/index.js:97:36)
  at parseSelector (/Users/chrisdamour/code/bwbot/node_modules/css-what/index.js:152:13)
```

I also tried
```
td:contains(commerce)
```

which returns no nodes

and
```
td:contains(/commerce/)
```

which returns
```
ERROR SyntaxError: missing closing parenthesis in :matches /commerce/)
  at parseSelector (/Users/chrisdamour/code/bwbot/node_modules/css-what/index.js:213:14)
  at parse (/Users/chrisdamour/code/bwbot/node_modules/css-what/index.js:82:13)
  at compileUnsafe (/Users/chrisdamour/code/bwbot/node_modules/css-select/lib/compile.js:31:14)
```

I also get this same error if i try something like
```
td:contains(commerce-ci)
```

**Comment by fb55** [comment]
Moved to https://github.com/fb55/css-what/issues/33

**Comment by fb55** [comment]
@drdamour `:matches` allows you to filter for elements matching a specific selector. It looks like you are tying to use it interchangeably with `:contains`, which is not possible.

**Comment by drdamour** [comment]
@fb55 please read  whole ticket i tried contains too and it didn’t work either

**Comment by drdamour** [comment]
Any chance to reopen for the contains problem? I guess I don’t care cause I’ve move on but next person might
