### ISSUE TITLE
SyntaxError: Unmatched selector

### ISSUE THREAD

**Issue by gijo-varghese** [cheeriojs/cheerio#1413]
I'm getting the following error while selecting an element:

```
SyntaxError: Unmatched selector:  .et_social_all_button i.et_social_icon.et_social_icon_all_button
        at parse (/Users/gijo/Desktop/workspace/flying-press-optimizer/node_modules/css-what/index.js:85:9)
        at compileUnsafe (/Users/gijo/Desktop/workspace/flying-press-optimizer/node_modules/css-select/lib/compile.js:31:14)
        at select (/Users/gijo/Desktop/workspace/flying-press-optimizer/node_modules/css-select/index.js:18:49)
        at CSSselect (/Users/gijo/Desktop/workspace/flying-press-optimizer/node_modules/css-select/index.js:41:9)
        at initialize.exports.find (/Users/gijo/Desktop/workspace/flying-press-optimizer/node_modules/cheerio/lib/api/traversing.js:40:21)
        at initialize.module.exports (/Users/gijo/Desktop/workspace/flying-press-optimizer/node_modules/cheerio/lib/cheerio.js:88:18)
        at new initialize (/Users/gijo/Desktop/workspace/flying-press-optimizer/node_modules/cheerio/lib/static.js:34:20)
        at initialize (/Users/gijo/Desktop/workspace/flying-press-optimizer/node_modules/cheerio/lib/static.js:31:14)
        at /Users/gijo/Desktop/workspace/flying-press-optimizer/src/optimizer/css/get-used-css.js:65:18
        at Array.filter (<anonymous>)
```

The selector syntax `.et_social_all_button i.et_social_icon.et_social_icon_all_button` seems to be valid. But what could be the reason for this error?

**Comment by cedaesca** [comment]
could it be referring to literally not finding a matching element for the selector?

**Comment by gijo-varghese** [comment]
I don't think so. Because if the element corresponding to the selector is not found, it should return 0.

**Comment by fb55** [comment]
The selector parses without issues with the current `1.0.0` branch.

**Comment by gijo-varghese** [comment]
@fb55 any eta for `1.0.0` release?

**Comment by fb55** [comment]
I'm trying to get out a new RC soon. The final release should follow soon afterwards.

**Comment by gijo-varghese** [comment]
@fb55 anyway I can use `1.0.0` in production? Maybe something like `npm i cheerio@next` is available?

**Comment by fb55** [comment]
There is a new RC that includes all changes.
