### ISSUE TITLE
content.ForEach is not a function

### ISSUE THREAD

**Issue by mrjackyliang** [cheeriojs/cheerio#1591]
Hello, I am a developer of a Homebridge plugin, and I am having a user report this error:

```
[12/23/2020, 4:09:41 PM] TypeError: content.forEach is not a function
    at parse (/homebridge/node_modules/homebridge-adt-pulse/node_modules/cheerio/lib/parse.js:38:15)
    at Function.exports.load (/homebridge/node_modules/homebridge-adt-pulse/node_modules/cheerio/lib/static.js:39:14)
    at /homebridge/node_modules/homebridge-adt-pulse/api.js:598:39
    at arrayMap (/homebridge/node_modules/homebridge-adt-pulse/node_modules/lodash/lodash.js:639:23)
    at Function.map (/homebridge/node_modules/homebridge-adt-pulse/node_modules/lodash/lodash.js:9580:14)
    at Request._callback (/homebridge/node_modules/homebridge-adt-pulse/api.js:597:28)
    at Request.self.callback (/homebridge/node_modules/homebridge-adt-pulse/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-adt-pulse/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
[12/23/2020, 4:09:41 PM] Got SIGTERM, shutting down Homebridge...
```

More details in [this issue](https://github.com/mrjackyliang/homebridge-adt-pulse/issues/39)

**Comment by 5saviahv** [comment]
Cheerio.load expects there to be array. Older versions was there condition for checking if it not array. Seems like it is lost due to optimizations.

**Comment by mrjackyliang** [comment]
Yeah, the input is an array. I don't get why it's having this error.

**Comment by 5saviahv** [comment]
sample from your code where it happens
``` javascript
...
const $ = cheerio.load(body);
const sensors = $('#orbSensorsList table tr.p_listRow').toArray();

const output = _.map(sensors, (sensor) => {
  const theSensor = cheerio.load(sensor);
  const theName = theSensor('a.p_deviceNameText').html();
  ...
})
...
```
variable `sensor` is single object (html node)

older version wraps it into array

**Comment by mrjackyliang** [comment]
Oh haha! Totally missed that actually.

**Comment by mrjackyliang** [comment]
<img width="844" alt="Screen Shot 2020-12-24 at 3 29 21 PM" src="https://user-images.githubusercontent.com/9779803/103105604-d1457f80-45fc-11eb-8dbf-b5ad3ce44fca.png">

Hmm could be the types need to be changed also, but yes, your suggestion works.

**Comment by fb55** [comment]
Thanks for the report! This was already fixed in https://github.com/cheeriojs/cheerio/commit/0855be618c327ab5adab0dedcc008e6e8c84eaf1, which should be part of a new release soon.

**Comment by boycce** [comment]
@fb55 thanks the fix works for me when sourcing the public repository. 

Our implementation:

```js
// v1.0.0-rc.5
$("table[table] tr").each((index, element) => {
   let issueHere = cheerio.load(element)
   // ...
```

**Comment by facundofarias** [comment]
Hello, any news about when this fix will be released?

**Comment by MegEdnazednav** [comment]
Hello, we are recently encountering this issue in our application as well, coming from a dependency that we are using. Could you tell us when the new version with the fix will be deployed? 
Thanks!
