### ISSUE TITLE
DomHandler is not a constructor

### ISSUE THREAD

**Issue by leo91000** [cheeriojs/cheerio#1829]
When I execute this code :
```ts
    import cheerio from 'cheerio';
    const $ = cheerio.load('<html><head></head><body><form></form></body><html>');
```

I get the error :
```
(RUN)   TypeError: DomHandler is not a constructor
(RUN)       at Object.parseDOM (FOLDER\node_modules\htmlparser2\lib\index.js:56:23)
(RUN)       at Function.exports.evaluate (FOLDER\node_modules\cheerio\lib\parse.js:41:22)
(RUN)       at module.exports (FOLDER\node_modules\cheerio\lib\parse.js:2321)
(RUN)       at Function.exports.load (FOLDER\node_modules\cheerio\lib\static.js:35:14)
...
```

I am using V0.22.0 with typescript

**Comment by fb55** [comment]
Please consider using `v1.0.0-rc.9`; `v0.22` is several years old by now and there are many things that could have gone wrong.

**Comment by Kevlun** [comment]
How did you solve it? @leo91000
