### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Tracer1337** [cheeriojs/cheerio#1941]
I use cheerio in my [crawler](https://github.com/Tracer1337/shitty-search) and sometimes I get this error:
```
 (node:16124) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at find (/var/www/shitty-search/node_modules/domutils/lib/querying.js:42:25)
    at Object.find (/var/www/shitty-search/node_modules/domutils/lib/querying.js:41:28)
    at find (/var/www/shitty-search/node_modules/cheerio-select/lib/index.js:288:21)
    at findElements (/var/www/shitty-search/node_modules/cheerio-select/lib/index.js:283:12)
    at Object.select (/var/www/shitty-search/node_modules/cheerio-select/lib/index.js:186:22)
    at initialize.find (/var/www/shitty-search/node_modules/cheerio/lib/api/traversing.js:54:30)
    at initialize.Cheerio (/var/www/shitty-search/node_modules/cheerio/lib/cheerio.js:87:30)
    at new initialize (/var/www/shitty-search/node_modules/cheerio/lib/load.js:39:28)
    at Parser.initialize [as $] (/var/www/shitty-search/node_modules/cheerio/lib/load.js:37:24)
    at Parser.getWords (/var/www/shitty-search/dist/Parser.java.js:34:14)
```
The corresponding file: https://github.com/Tracer1337/shitty-search/blob/master/packages/crawler/src/Parser.java.ts#L35

I don't know why it occurs nor how to reproduce it, but my crawler has thrown it two times while crawling 1500 pages.

**Comment by aliyome** [comment]
I have encountered a similar error. In my case, the error occurred when the target was not html.

**Comment by fb55** [comment]
This is an issue when a document is nested thousands of levels deep, which the vast majority of documents will not be.

For this issue: You likely don't need a DOM tree, and building one up is wasting your resources. Have a look at a package such as https://github.com/inikulin/parse5/tree/master/packages/parse5-sax-parser
