### ISSUE TITLE
Bumping css-select version to 4.2.1 for tag 0.22.0 causing issue

### ISSUE THREAD

**Issue by karan8112** [cheeriojs/cheerio#2331]
Test Cases Failed with following Error: **TypeError: select is not a function
    at module.exports.exports.find (lib/api/traversing.js:40:21)
    at new module.exports (lib/cheerio.js:86:18)
    at module.exports (lib/cheerio.js:31:42)
    at Context.<anonymous> (test/cheerio.js:72:18)
    at processImmediate (internal/timers.js:464:21)**

**Comment by fb55** [comment]
Feel free to use the current RCs, which include all updates!
