### ISSUE TITLE
Not works with htmlparser2

### ISSUE THREAD

**Issue by lublak** [cheeriojs/cheerio#2401]
Currently  i tried cheerio with htmlparser2.
But it throws an error:

```ts
const dom = htmlparser2.parseDocument(data);
const $ = cheerio.load(dom);
$.html() // throws the error
```

```
H:\testproject\node_modules\parse5-htmlparser2-tree-adapter\lib\index.js:283
            namespace: element['x-attribsNamespace'][name],
                                                    ^

TypeError: Cannot read properties of undefined (reading 'href')
    at Object.exports.getAttrList (H:\testproject\node_modules\parse5-htmlparser2-tree-adapter\lib\index.js:283:53)
    at Serializer._serializeAttributes (H:\testproject\node_modules\parse5\lib\serializer\index.js:99:40)
    at Serializer._serializeElement (H:\testproject\node_modules\parse5\lib\serializer\index.js:67:14)
    at Serializer._serializeChildNodes (H:\testproject\node_modules\parse5\lib\serializer\index.js:50:26)
    at Serializer._serializeElement (H:\testproject\node_modules\parse5\lib\serializer\index.js:93:18)
    at Serializer._serializeChildNodes (H:\testproject\node_modules\parse5\lib\serializer\index.js:50:26)
    at Serializer._serializeElement (H:\testproject\node_modules\parse5\lib\serializer\index.js:93:18)
    at Serializer._serializeChildNodes (H:\testproject\node_modules\parse5\lib\serializer\index.js:50:26)
    at Serializer._serializeElement (H:\testproject\node_modules\parse5\lib\serializer\index.js:93:18)
    at Serializer._serializeChildNodes (H:\testproject\node_modules\parse5\lib\serializer\index.js:50:26)
```

**Comment by lublak** [comment]
i edit this code by hand to get it work:

![grafik](https://user-images.githubusercontent.com/44057030/157434473-9b06321e-5b00-49ae-bd59-e26c2379bbcf.png)

**Comment by fb55** [comment]
This will be fixed with the next version. For now, you can try

```js
const $ = cheerio.load(data, { _useHtmlParser2: true });
$.html() // throws the error
```

The `{ _useHtmlParser2: true }` forces Cheerio to use `htmlparser2`.

**Comment by lublak** [comment]
@fb55 thanks for the answer :) this works fine for now.
