### ISSUE TITLE
Difference between parse5 and htmlparse2 ASTs => null bug with ``

### ISSUE THREAD

**Issue by hsablonniere** [cheeriojs/cheerio#2522]
Hello @fb55

I'm sorry if I'm not writing the issue in the right repo or if the title is not precise enough.

## Context

While using a sibling selector with a match all, something like `.my-class + *`, I encountered a null bug with `cheerio`:

```
Cannot read properties of undefined (reading 'type')
```

## Looking for the root cause

I tried to identify the root cause of this bug and it seems like, it's a combination of:

* `parse5-htmlparser2-tree-adapter` returning `undefined` for `prev` on some AST nodes like the Doctype while `htmlparser2` returns `null`
  * I'm not sure where this can be fixed and it seems like the modern version of the adapter don't have this problem
* `domutils` having a strict check `prev !== null` instead of `prev != null` in `prevElementSibling`
  * https://github.com/fb55/domutils/blob/master/src/traversal.ts#L123

## Reproducing the bug

Using these dependencies (the versions used by cheerio `^1.0.0-rc.10`), you can trigger the bug:

* "domutils": "^2.8.0",
* "htmlparser2": "^6.1.0",
* "parse5": "^6.0.1",
* "parse5-htmlparser2-tree-adapter": "^6.0.1"

And with this code:

```js
import { parse } from 'parse5';
import adapter from 'parse5-htmlparser2-tree-adapter';
import { parseDOM } from 'htmlparser2';
import { prevElementSibling } from 'domutils';

const html = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="FR"></html>`;

{
  const dom = parseDOM(html);
  const htmlTag = dom.find((t) => t.type === 'tag' && t.name === 'html');
  console.log('with htmlparser2');
  console.log('htmlTag.type', htmlTag.type);
  console.log('htmlTag.prev.prev', htmlTag.prev.prev);
  try {
    console.log('prevElementSibling', prevElementSibling(htmlTag));
  }
  catch (e) {
    console.error(e);
  }
}

{
  const dom = parse(html, { treeAdapter: adapter });
  const htmlTag = dom.children.find((t) => t.type === 'tag' && t.name === 'html');
  console.log('with parse5 + parse5-htmlparser2-tree-adapter');
  console.log('htmlTag.type', htmlTag.type);
  console.log('htmlTag.prev.prev', htmlTag.prev.prev);
  try {
    console.log('prevElementSibling', prevElementSibling(htmlTag));
  }
  catch (e) {
    console.error(e);
  }
}
```

We get this:

```
with htmlparser2
htmlTag.type tag
htmlTag.prev.prev null
prevElementSibling null

with parse5 + parse5-htmlparser2-tree-adapter
htmlTag.type tag
htmlTag.prev.prev undefined
TypeError: Cannot read properties of undefined (reading 'type')
    at isTag (/home/hsablonniere/dev/domutils-test/node_modules/domelementtype/lib/index.js:32:18)
    at isTag (/home/hsablonniere/dev/domutils-test/node_modules/domhandler/lib/node.js:321:39)
    at prevElementSibling (/home/hsablonniere/dev/domutils-test/node_modules/domutils/lib/traversal.js:113:53)
    at file:///home/hsablonniere/dev/domutils-test/index.js:29:39
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

## What's next?

It seems like moving to latest versions of each dependencies for cheerio could fix the bug but I think `domutils` should change the code from `!== null` to `!= null` just to be safe.

I can help by writing some PRs or just testing new releases if necessary, please let me know :wink:

**Comment by fb55** [comment]
This has already been fixed on `main`. 

The difference between the parser interfaces was one of the main reasons I didn't publish a final 1.0.0.

**Comment by fb55** [comment]
One thing that would be super helpful is if you could add a unit test for this.
