### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by tushar-sg** [cheeriojs/cheerio#2587]
We started facing this issue after upgrading to rc.11.

This happens when we execute the following line.

```js
const $ = load(html, { decodeEntities: false }, false);
```

```text
TypeError: Cannot read properties of undefined (reading '0')
\n    at t.Tokenizer._matchNamedCharacterReference (/var/task/vendor.js:41:178075)
\n    at t.Tokenizer._stateNamedCharacterReference (/var/task/vendor.js:41:217889)
\n    at t.Tokenizer._stateCharacterReference (/var/task/vendor.js:41:217692)
\n    at t.Tokenizer._callState (/var/task/vendor.js:41:184305)
\n    at t.Tokenizer._runParsingLoop (/var/task/vendor.js:41:173340)
\n    at t.Tokenizer.write (/var/task/vendor.js:41:173606)
\n    at Function.parse (/var/task/vendor.js:41:129686)
\n    at t.parse (/var/task/vendor.js:41:105635)
\n    at t.parseWithParse5 (/var/task/vendor.js:1:1343729)
\n    at /var/task/vendor.js:1:1338701
```

**Comment by fb55** [comment]
Could you provide the markup you are trying to parse?

**Comment by fb55** [comment]
@tushar-sg I'd love to tackle this, but would need the relevant mark-up. Closing this as not reproducible for now.
