### ISSUE TITLE
Unable to load document

### ISSUE THREAD

**Issue by Automized** [cheeriojs/cheerio#2660]
when i do 
```js
const $ = cheerio.load('response data')
```

if sends me back this error, not sure what is it. The response is pure HTML.

```js
for (let i = 0, current = decode_js_1.htmlDecodeTree[0]; i >= 0; cp = this._consume()) {
                                                            ^

TypeError: Cannot read property '0' of undefined```

**Comment by fb55** [comment]
Please provide the full response, otherwise I'm unable to reproduce. Please also provide some information on your environment.

**Comment by Automized** [comment]
Cheerio Version: 7.10.0
Node Version: 16.0.0
OS: Windows 11

```js

 C:\Users\automized\Desktop\development\node_modules\parse5\dist\cjs\tokenizer\index.js:497
 for (let i = 0, current = decode_js_1.htmlDecodeTree[0]; i >= 0; cp = this._consume()) {
                                                            ^                                                                                                                                                                                   TypeError: Cannot read property '0' of undefined
    at Tokenizer._matchNamedCharacterReference (C:\Users\automized\Desktop\development\node_modules\parse5\dist\cjs\tokenizer\index.js:497:61)
    at Tokenizer._stateNamedCharacterReference (C:\Users\automized\Desktop\development\node_modules\parse5\dist\cjs\tokenizer\index.js:2784:34)
    at Tokenizer._stateCharacterReference (C:\Users\automized\Desktop\development\node_modules\parse5\dist\cjs\tokenizer\index.js:2774:18)
    at Tokenizer._callState (C:\Users\automized\Desktop\development\node_modules\parse5\dist\cjs\tokenizer\index.js:848:22)
    at Tokenizer._runParsingLoop (C:\Users\automized\Desktop\development\node_modules\parse5\dist\cjs\tokenizer\index.js:227:22)
    at Tokenizer.write (C:\Users\automized\Desktop\development\node_modules\parse5\dist\cjs\tokenizer\index.js:252:14)
    at Function.parse (C:\Users\automized\Desktop\development\node_modules\parse5\dist\cjs\parser\index.js:101:26)
    at parse (C:\Users\automized\Desktop\development\node_modules\parse5\dist\cjs\index.js:41:30)
    at parseWithParse5 (C:\Users\automized\Desktop\development\node_modules\cheerio\lib\parsers\parse5-adapter.js:34:30)
    at C:\Users\automized\Desktop\development\node_modules\cheerio\lib\index.js:47:51

**Comment by fb55** [comment]
Please also provide the markup – this is the most crucial to reproduce the issue. If you can't, please try to identify a subset you can share, that causes the issue.

**Comment by Automized** [comment]
Hi, Sorry for the late reply. I do not unstand what you mean by `subset`.

I was able to fix the issue though by simple doing `npm i cheerio@v1.0.0-rc.5`

**Comment by fb55** [comment]
It seems like this is an issue with the latest release. If you can provide the markup, I will do my best to figure out what is happening, so that you won't be stuck on an old release indefinitely.

**Comment by Automized** [comment]
yes okay. 

The website I was getting the data from was a simple get request to `https://rentry.co`

**Comment by fb55** [comment]
I'm unfortunately unable to reproduce this. Happy to revisit this issue should I receive HTML that breaks the parser (does not need to be reduced, I'm happy to do this myself).
