### ISSUE TITLE
  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/traversing' is not defined by "exports" in package.json

### ISSUE THREAD

**Issue by ChiatzenW** [cheeriojs/cheerio#2732]
Ran `npm install cheerio` in pwd.
These are in my js file:
```
cheerio = require("cheerio");
...
  $ = cheerio.load(html);
  $("body").append(data);
  $("#date").text(date);
  $("#status").text(statSus);
  process.stdout._write(html);
...
```
when running:
```
> node serve.js

node:internal/modules/cjs/loader:499
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/traversing' is not defined by "exports" in /pwd/node_modules/cheerio/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:439:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:718:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (pwd/serve.js:1:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

**Comment by brookmg** [comment]
I am experiencing a similar issue on deployment. 
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/attributes' is not defined by "exports" in /opt/render/project/src/node_modules/cheerio/package.json
Sep 1 02:24:45 PM      at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
Sep 1 02:24:45 PM      at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
Sep 1 02:24:45 PM      at resolveExports (internal/modules/cjs/loader.js:437:36)
Sep 1 02:24:45 PM      at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)
Sep 1 02:24:45 PM      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:8Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/api/attributes' is not defined by "exports" in /opt/render/project/src/node_modules/cheerio/package.json
Sep 1 02:24:45 PM      at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
Sep 1 02:24:45 PM      at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
Sep 1 02:24:45 PM      at resolveExports (internal/modules/cjs/loader.js:437:36)
Sep 1 02:24:45 PM      at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)
Sep 1 02:24:45 PM      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
Sep 1 02:24:45 PM      at Function.Module._load (internal/modules/cjs/loader.js:730:27)
Sep 1 02:24:45 PM      at Module.require (internal/modules/cjs/loader.js:957:19)
Sep 1 02:24:45 PM      at require (internal/modules/cjs/helpers.js:88:18)
Sep 1 02:24:45 PM      at Object.<anonymous> (/opt/render/project/src/dist/api/v1/engine/engine.controller.js:11:19)
Sep 1 02:24:45 PM      at Module._compile (internal/modules/cjs/loader.js:1068:30) {
Sep 1 02:24:45 PM    code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
Sep 1 02:24:45 PM  }72:27)
Sep 1 02:24:45 PM      at Function.Module._load (internal/modules/cjs/loader.js:730:27)
Sep 1 02:24:45 PM      at Module.require (internal/modules/cjs/loader.js:957:19)
Sep 1 02:24:45 PM      at require (internal/modules/cjs/helpers.js:88:18)
Sep 1 02:24:45 PM      at Object.<anonymous> (/opt/render/project/src/dist/api/v1/engine/engine.controller.js:11:19)
Sep 1 02:24:45 PM      at Module._compile (internal/modules/cjs/loader.js:1068:30) {
Sep 1 02:24:45 PM    code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
Sep 1 02:24:45 PM  }
```

**Comment by brookmg** [comment]
False alarm, it was a bad import in the codebase.

**Comment by fb55** [comment]
You shouldn't have to import this path. Feel free to expand on why this is needed, but I can't think of a reason you wouldn't want to import the main module.
