### ISSUE TITLE
$.extract is not a function

### ISSUE THREAD

**Issue by soeasyjx** [cheeriojs/cheerio#3233]
### Description
When I followed the tutorial in the [official documentation](https://cheerio.js.org/docs/advanced/extract), using the extract api, I displayed the error directly in the terminal after running it
```error
 axios_demo % node index
TypeError: $.extract is not a function
    at start (/Users/jiangxin/test_project/package_test/axios_demo/index.js:75:16)
    at Object.<anonymous> (/Users/jiangxin/test_project/package_test/axios_demo/index.js:99:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```
### version 
- "node":"v18.14.1"
- "cheerio": "1.0.0-rc.12"

### code
>It's actually a snippet of code submitted in the official documentation

```js
const cheerio = require("cheerio");
    const $ = cheerio.load(`
  <ul>
    <li>One</li>
    <li>Two</li>
    <li class="blue sel">Three</li>
    <li class="red">Four</li>
  </ul>
`);
const data = $.extract({
    red: '.red',
  });
```
**Personally, I don't think this kind of mistake should have happened**

**Comment by fb55** [comment]
Thanks @punkish!

**Comment by vibl** [comment]
See https://github.com/cheeriojs/cheerio/issues/3165#issuecomment-2156304677
