### ISSUE TITLE
Failing test suits with enzyme since 1.0.0

### ISSUE THREAD

**Issue by eladonline** [cheeriojs/cheerio#3999]
Hello, since the latest update to version 1.0.0 
enzyme tests suits started failing 
 failure message 
![image](https://github.com/user-attachments/assets/41f4fafb-a21d-4cca-ac2b-c8f087ee62a1)

I solved it by downgrading cheerio to version "1.0.0-rc.12"
for everyone who have same problem to solve this I override the package dependency 
just add this to the package.json 
![image](https://github.com/user-attachments/assets/997c2543-14f3-4e72-ac41-5aadd38716fa)

**Comment by mjancarik** [comment]
Hello, 

Could you return back export declaration for `lib/utils` to package.json https://github.com/cheeriojs/cheerio/commit/caab0694ff5384e12c1c29ba80414174943af3c9?

**Comment by Filipoliko** [comment]
For us, there was a bit different error message, but the suggested hotfix resolved our issue.

```
  ● Test suite failed to run
    Cannot find module 'cheerio/lib/utils' from '../node_modules/enzyme/build/Utils.js'
    Require stack:
      /builds/cns/campus/backend/node_modules/enzyme/build/Utils.js
      /builds/cns/campus/backend/node_modules/enzyme/build/ReactWrapper.js
      /builds/cns/campus/backend/node_modules/enzyme/build/index.js
      jest.setup.js
      at Resolver._throwModNotFoundError (../node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.<anonymous> (../node_modules/enzyme/build/Utils.js:84:14)
```

As enzyme is not being developed anymore, this might be very big problem for all enzyme library users (just about 1.8 mil in the past week).
