### ISSUE TITLE
ReferenceError: ReadableStream is not defined - fetch/response.js:527:3

### ISSUE THREAD

**Issue by pietheinstrengholt** [cheeriojs/cheerio#4151]
I've upgraded from 1.0.0-rc.12 to 1.0.0 and am experiencing an issue with one of the dependencies, which was not present before. Does anyone know what could be causing this?

```
/mnt/c/GitHub/rssmonster/server/node_modules/undici/lib/web/fetch/response.js:527
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/mnt/c/GitHub/rssmonster/server/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/mnt/c/GitHub/rssmonster/server/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Form1ca** [comment]
same error with node 16.16

**Comment by wartab** [comment]
cheerio requires node 18.17 or later.

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)
