### ISSUE TITLE
When desired value is null, `$.extract()` fails catastrophically.

### ISSUE THREAD

**Issue by Technical-13** [cheeriojs/cheerio#4239]
Code:
```JavaScript
$.extract( { links: [ { selector: 'a', value: 'href' } ] } );
```
On site with links that have no href:
![no href](https://github.com/user-attachments/assets/d943f835-3b04-4b17-bcc3-38b2682c945d)
Gives:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at parse (/home/container/node_modules/css-what/lib/commonjs/parse.js:84:29)
    at Object.select (/home/container/node_modules/cheerio-select/lib/index.js:191:68)
    at LoadedCheerio._findBySelector (/home/container/node_modules/cheerio/dist/commonjs/api/traversing.js:115:30)
    at LoadedCheerio.extract (/home/container/node_modules/cheerio/dist/commonjs/api/extract.js:39:28)
    at Function.extract (/home/container/node_modules/cheerio/dist/commonjs/static.js:165:24)
    at /home/container/commands/admin/foo.js:16:30
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by fb55** [comment]
Seems like an issue in `prop`, where the "href" prop doesn't support elements without this value. PRs welcome!

**Comment by fb55** [comment]
@Technical-13 I added some tests for what I thought would be the issue in #4322, but all of them succeed. Please provide actual markup to make it possible to replicate the issue — there is not enough here to understand your issue.
