### ISSUE TITLE
SyntaxError: Unexpected token '??=' ?[90m    at wrapSafe (internal/modules/cjs/loader.js:1029:16)?[39m

### ISSUE THREAD

**Issue by zhaosheng808** [cheeriojs/cheerio#4289]
nodeVersion: v14.21.3
cheerio@1.0.0-rc.10 update to cheerio@1.0.0，  The following error will be prompted:
```
SyntaxError: Unexpected token '??='
?[90m    at wrapSafe (internal/modules/cjs/loader.js:1029:16)?[39m
?[90m    at Module._compile (internal/modules/cjs/loader.js:1078:27)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:979:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:819:12)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:1003:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:107:18)?[39m
    at Object.<anonymous> (F:\work-gitlab\video-grab\node_modules\?[4mundici?[24m\lib\dispatcher\client.js:8:14)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1114:14)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)?[39m

```
I found that it should be caused by this new dependencies `"undici": "^6.19.5",`.
[undici 6.19.5](https://github.com/cheeriojs/cheerio/blob/5e39abd9d75cbacfb03802dfc7e2ee48b84a1b6f/package.json#L127)
I hope to achieve compatibility。

**Comment by fb55** [comment]
Unfortunately Cheerio's minimum NodeJS version had to be bumped to 18. Please update to a runtime that is not abandoned.
