### ISSUE TITLE
SyntaxError: unmatched pseudo-class :eq

### ISSUE THREAD

**Issue by breezewish** [cheeriojs/cheerio#429]
When I'm trying to use `$(...).eq(..)`:

```
SyntaxError: unmatched pseudo-class :eq
    at module.exports.compile [as pseudo] (/Users/breeswish/Development/Web/pj/node_modules/cheerio/node_modules/CSSselect/lib/pseudos.js:333:10)
    at /Users/breeswish/Development/Web/pj/node_modules/cheerio/node_modules/CSSselect/lib/compile.js:35:26
    at Array.reduce (native)
    at compileRules (/Users/breeswish/Development/Web/pj/node_modules/cheerio/node_modules/CSSselect/lib/compile.js:33:24)
    at Array.map (native)
    at compileUnsafe (/Users/breeswish/Development/Web/pj/node_modules/cheerio/node_modules/CSSselect/lib/compile.js:27:4)
    at select (/Users/breeswish/Development/Web/pj/node_modules/cheerio/node_modules/CSSselect/index.js:17:43)
    at CSSselect (/Users/breeswish/Development/Web/pj/node_modules/cheerio/node_modules/CSSselect/index.js:40:9)
    at exports.find (/Users/breeswish/Development/Web/pj/node_modules/cheerio/lib/api/traversing.js:7:21)
```

**Comment by maleja111** [comment]
i'm sorry but install https://github.com/watson/cheerio-eq not solved the problem

**Comment by dzcpy** [comment]
You can try to use `nth-child` instead. `eq(0)` === `nth-child(1)`, `eq(1)` === `nth-child(2)`, etc.
