### ISSUE TITLE
TypeError: Cannot read property 'parent' of null

### ISSUE THREAD

**Issue by ZatheGFX** [cheeriojs/cheerio#596]
I am receiving this error:

```
/home/ubuntu/workspace/node_modules/cheerio/lib/parse.js:55
    var oldParent = node.parent || node.root,
                        ^
TypeError: Cannot read property 'parent' of null
    at Function.exports.update (/home/ubuntu/workspace/node_modules/cheerio/lib/parse.js:55:25)
    at module.exports (/home/ubuntu/workspace/node_modules/cheerio/lib/parse.js:17:11)
    at Function.exports.load (/home/ubuntu/workspace/node_modules/cheerio/lib/static.js:19:14)
    at http.get.cheerio.load.normalizeWhitespace (/home/ubuntu/workspace/main.js:153:15)
    at IncomingMessage.result (/home/ubuntu/workspace/node_modules/client-http/lib/clienthttp.js:71:25)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:938:16
    at process._tickCallback (node.js:419:13)
```

Has anyone else experienced this issue?

I am not exactly sure where I should be looking in my code to find this issue. I am scraping multiple sites every 30 seconds using cron.

**Comment by roverliang** [comment]
I'dont konw why  the error is show 。
