### ISSUE TITLE
Issue installing dependencies on windows

### ISSUE THREAD

**Issue by sergei1152** [cheeriojs/cheerio#664]
Hey, I cant seem to install the cheerio dependencies on windows. It has something to do with gyp. I'm running Windows 7 with node 0.12 and cygwin. 

```
 npm install
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})

> contextify@0.1.13 install C:\cygwin64\home\nodebot1\svt-tool\node_modules\cheerio\node_modules\jsdom\node_modules\contextify
> node-gyp rebuild

C:\cygwin64\home\nodebot1\svt-tool\node_modules\cheerio\node_modules\jsdom\node_modules\contextify>node "C:\Users\nodebot1\IBMSVT32\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp WARN node-gyp configure common.gypi Unable to find a version of common.gypi to copy to the node headers location, your build may not work as expected
child_process: customFds option is deprecated, use stdio instead.
Traceback (most recent call last):
  File "C:\Users\nodebot1\IBMSVT32\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 15, in <module>
    import gyp
ImportError: No module named gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\nodebot1\IBMSVT32\node_modules\npm\node_modules\node-gyp\lib\configure.js:462:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\nodebot1\\IBMSVT32\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\cygwin64\home\nodebot1\svt-tool\node_modules\cheerio\node_modules\jsdom\node_modules\contextify
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\nodebot1\\IBMSVT32\\node.exe" "C:\\Users\\nodebot1\\IBMSVT32\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.13 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

pm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin64\home\nodebot1\svt-tool\node_modules\cheerio\npm-debug.log

```

**Comment by fb55** [comment]
That's an issue with jsdom, which is only used for benchmarking. Unless you are trying to improve cheerio's performance, you should be good; just ignore the error.
