### ISSUE TITLE
Unmatched selector when using quotes with :has

### ISSUE THREAD

**Issue by seishun** [cheeriojs/cheerio#682]
```js
var cheerio = require('cheerio');
var html = "<html><div id='exists'><div class='.ship'>Some text</div></div></html>";
var $ = cheerio.load(html);
$(html).find('div:has(".ship")');
```

```
                                throw new SyntaxError("Unmatched selector: " + firstChar + selector);
                                      ^
SyntaxError: Unmatched selector: ".ship"
    at parse (E:\Dropbox\Documents\node_modules\cheerio\node_modules\css-select\node_modules\css-what\index.js:172:11)
    at compileUnsafe (E:\Dropbox\Documents\node_modules\cheerio\node_modules\css-select\lib\compile.js:30:14)
    at Object.filters.has (E:\Dropbox\Documents\node_modules\cheerio\node_modules\css-select\lib\compile.js:157:13)
    at module.exports.compile [as pseudo] (E:\Dropbox\Documents\node_modules\cheerio\node_modules\css-select\lib\pseudos.js:326:24)
    at E:\Dropbox\Documents\node_modules\cheerio\node_modules\css-select\lib\compile.js:80:26
    at Array.reduce (native)
    at Object.compileRules (E:\Dropbox\Documents\node_modules\cheerio\node_modules\css-select\lib\compile.js:78:15)
    at Array.map (native)
    at compileToken (E:\Dropbox\Documents\node_modules\cheerio\node_modules\css-select\lib\compile.js:65:4)
    at compileUnsafe (E:\Dropbox\Documents\node_modules\cheerio\node_modules\css-select\lib\compile.js:31:9)
```

Reproducible with cheerio installed from either npm or git.

**Comment by fb55** [comment]
This is fixed with #681. You won't match any elements, though, as the class is `.ship`; you would need to search for `div:has(.\\.ship)`.
