### ISSUE TITLE
SyntaxError: Unmatched selector: '.next'

### ISSUE THREAD

**Issue by Russ93** [cheeriojs/cheerio#710]
Selector:
div#pagination a.results:has('.next')

```
[ERROR] 11:32:40 SyntaxError
SyntaxError: Unmatched selector: '.next'
  at parse (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/node_modules/css-what/index.js:172:11)
  at compileUnsafe (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/lib/compile.js:30:14)
  at Object.filters.has (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/lib/compile.js:157:13)
  at [object Object].module.exports.compile [as pseudo] (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/lib/pseudos.js:326:24)
  at /Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/lib/compile.js:80:26
  at Array.reduce (native)
  at Object.compileRules (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/lib/compile.js:78:15)
  at Array.map (native)
  at compileToken (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/lib/compile.js:65:4)
  at compileUnsafe (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/lib/compile.js:31:9)
  at select (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/index.js:17:43)
  at CSSselect (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/node_modules/css-select/index.js:40:9)
  at [object Object].exports.find (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/lib/api/traversing.js:32:21)
  at [object Object].module.exports (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/lib/cheerio.js:86:18)
  at new initialize (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/lib/static.js:26:20)
  at initialize (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/cheerio/lib/static.js:23:14)
  at /Users/russellbenton/Git Hub/portlight_pipeline/app/workers/lib/collectRetail.coffee:38:18
  at Request.handleRequestResponse [as _callback] (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/unirest/index.js:459:25)
  at Request.self.callback (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/unirest/node_modules/request/request.js:373:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/unirest/node_modules/request/request.js:1318:14)
  at Request.emit (events.js:129:20)
  at Stream.<anonymous> (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/unirest/node_modules/request/request.js:1266:12)
  at Stream.emit (events.js:104:17)
  at Unzip.<anonymous> (/Users/russellbenton/Git Hub/portlight_pipeline/app/node_modules/unirest/index.js:493:22)
  at Unzip.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

I've tested the same selector in jquery
would you like an html sample?

**Comment by fb55** [comment]
I assume the failure was due to the quotes around the selector, which is fixed.
