### ISSUE TITLE
Object has no method 'wrap'?

### ISSUE THREAD

**Issue by joelabair** [cheeriojs/cheerio#731]
bash >node 
> var cheerio = require('cheerio'),
...     $ = cheerio.load('<ul id="fruits">...</ul>');
undefined
> $('ul').wrap($('<a></a>'));
TypeError: Object <ul id="fruits">...</ul> has no method 'wrap'
    at repl:1:9
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)

What am I doing wrong here?

**Comment by jugglinmike** [comment]
The `wrap`method has landed in `master` but it has not been released on npm. The next minor release of the library (following 0.19.0) will include it. If you'd like to use `wrap` today, you can include Cheerio [using a git SHA in your `package.json`](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies). Just remember that you'll be locked to that commit, so you won't get new releases automatically.

**Comment by joelabair** [comment]
thanks
