### ISSUE TITLE
Why is the cheerio node module producing this error?

### ISSUE THREAD

**Issue by dearfrankg** [cheeriojs/cheerio#761]
Why am I getting errors with both cheerio and cheerio-cli?

```
cat van.html | cheerio .instagram-media -a src

cheerio-cli processing HTML produces:

---------------------------------------------------------------
https://instagram.com/p/8UZuhZEiYq/embed/captioned/?v=5
https://instagram.com/p/8US9hPEo_C/embed/captioned/?v=5
https://instagram.com/p/8UTEDJDIlU/embed/captioned/?v=5
/Users/frankg/.nvm/versions/node/v4.1.0/lib/node_modules/cheerio-cli/bin/cheerio:28
      process.stdout.write($res.eq(i)['attr'](program.attr).toString());
                                                           ^

TypeError: Cannot read property 'toString' of undefined
    at Socket.<anonymous> (/Users/frankg/.nvm/versions/node/v4.1.0/lib/node_modules/cheerio-cli/bin/cheerio:28:57)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
---------------------------------------------------------------

//////////////////////////////////////////////

//casperjs
var cheerio = require('cheerio');
var casper = require('casper').create();

var url = 'http://www......';

casper.start(url, function() {
  var js = this.evaluate(function() {
    return document;
  });

  var HTML = js.all[0].outerHTML;
  $ = cheerio.load(HTML);

});
casper.run();

//////////////////////////////////////////////


casperjs getHTML.js

Runnung the script produces an error on the line where cheerio parses HTML:

1
Error: Cannot find module 'util'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /Users/frankg/dev/code/demo-apps/scraping/casperjs-taleo-job-scraper/node_modules/htmlparser2/lib/Parser.js:120
  /Users/frankg/dev/code/demo-apps/scraping/casperjs-taleo-job-scraper/node_modules/htmlparser2/lib/Parser.js:351
250546
TypeError: '[object Object]' is not a constructor (evaluating 'new Parser(handler, options)')
  /Users/frankg/dev/code/demo-apps/scraping/casperjs-taleo-job-scraper/node_modules/htmlparser2/lib/index.js:41
  /Users/frankg/dev/code/demo-apps/scraping/casperjs-taleo-job-scraper/node_modules/cheerio/lib/parse.js:28
  /Users/frankg/dev/code/demo-apps/scraping/casperjs-taleo-job-scraper/node_modules/cheerio/lib/parse.js:10
  /Users/frankg/dev/code/demo-apps/scraping/casperjs-taleo-job-scraper/node_modules/cheerio/lib/static.js:19
  /Users/frankg/dev/code/demo-apps/scraping/casperjs-taleo-job-scraper/getHTML.js:20
  /Users/frankg/.nvm/versions/node/v4.1.0/lib/node_modules/casperjs/modules/casper.js:1553 in runStep
  /Users/frankg/.nvm/versions/node/v4.1.0/lib/node_modules/casperjs/modules/casper.js:399 in checkStep
```

**Comment by fb55** [comment]
The first appears to be a `cheerio-cli` bug, where it doesn't handle the case that an attribute is not present. This is the first time I've heard of `cheerio-cli` and this is definitely the wrong repo for this bug.

The second runs the code within PhantomJS, which doesn't have a `util` module, which several of cheerio's dependencies depend on. You probably want to run a browserified version.

**Comment by MichaelTSS** [comment]
+1
