### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by doug-wade** [cheeriojs/cheerio#874]
Repro:

```
dougwade npm-experiments/cannot-find-cheerio » npm init --yes
Wrote to /Users/doug.wade/npm-experiments/cannot-find-cheerio/package.json:

{
  "name": "cannot-find-cheerio",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


dougwade npm-experiments/cannot-find-cheerio » npm i cheerio
npm WARN package.json cannot-find-cheerio@1.0.0 No description
npm WARN package.json cannot-find-cheerio@1.0.0 No repository field.
npm WARN package.json cannot-find-cheerio@1.0.0 No README data
cheerio@0.21.0 node_modules/cheerio
├── entities@1.1.1
├── dom-serializer@0.1.0 (domelementtype@1.1.3)
├── lodash.flatten@4.2.0 (lodash._baseflatten@4.2.1)
├── lodash.assignin@4.0.9 (lodash.rest@4.0.3, lodash.keysin@4.1.4)
├── lodash.pick@4.2.1 (lodash.rest@4.0.3, lodash._baseflatten@4.2.1)
├── lodash.merge@4.4.0 (lodash.isplainobject@4.0.4, lodash._root@3.0.1, lodash.rest@4.0.3, lodash.keysin@4.1.4, lodash._baseclone@4.5.7)
├── lodash.bind@4.1.4 (lodash.rest@4.0.3, lodash._createwrapper@4.0.5)
├── lodash.defaults@4.0.1 (lodash.rest@4.0.3, lodash.assigninwith@4.0.7)
├── css-select@1.2.0 (boolbase@1.0.0, css-what@2.1.0, nth-check@1.0.1, domutils@1.5.1)
├── lodash.filter@4.4.0 (lodash._basefilter@4.0.1, lodash._baseiteratee@4.7.0)
├── lodash.reject@4.4.0 (lodash._basefilter@4.0.1, lodash._baseiteratee@4.7.0)
├── lodash.some@4.4.0 (lodash._baseeach@4.1.3, lodash._baseiteratee@4.7.0)
├── lodash.map@4.4.0 (lodash._baseeach@4.1.3, lodash._baseiteratee@4.7.0)
├── lodash.foreach@4.3.0 (lodash._baseeach@4.1.3, lodash._baseiteratee@4.7.0)
├── lodash.reduce@4.4.0 (lodash._basereduce@3.0.2, lodash._baseeach@4.1.3, lodash._baseiteratee@4.7.0)
└── htmlparser2@3.9.1 (domelementtype@1.3.0, inherits@2.0.1, domutils@1.5.1, domhandler@2.3.0, readable-stream@2.1.4)
dougwade npm-experiments/cannot-find-cheerio » node
> var cheerio = require('cheerio');
Error: Cannot find module 'cheerio'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:1:15
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
```

**Comment by doug-wade** [comment]
Looks like the root cause is that the main file is missing

```
dougwade npm-experiments/cannot-find-cheerio » cat node_modules/cheerio/package.json
{
  "name": "cheerio",
  "version": "0.21.0",
  ...
  "main": "./index.js",
  ...
}
dougwade npm-experiments/cannot-find-cheerio » ls node_modules/cheerio/
History.md  Readme.md  lib  node_modules  package.json
```

**Comment by doug-wade** [comment]
I forked and pulled, and nothing seems obvious -- 

```
dougwade code/cheerio ‹master› » npm i
...
dougwade code/cheerio ‹master› » node
> var cheerio = require('.')
undefined
```

**Comment by doug-wade** [comment]
Looks like I got a bum version cached in `sinopia`

```
dougwade npm-experiments/cannot-find-cheerio » npm config set registry https://registry.npmjs.org/
dougwade npm-experiments/cannot-find-cheerio » rm -r node_modules
dougwade npm-experiments/cannot-find-cheerio » npm i cheerio
npm WARN package.json cannot-find-cheerio@1.0.0 No description
npm WARN package.json cannot-find-cheerio@1.0.0 No repository field.
npm WARN package.json cannot-find-cheerio@1.0.0 No README data
cheerio@0.20.0 node_modules/cheerio
├── entities@1.1.1
├── dom-serializer@0.1.0 (domelementtype@1.1.3)
├── css-select@1.2.0 (boolbase@1.0.0, css-what@2.1.0, nth-check@1.0.1, domutils@1.5.1)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domutils@1.5.1, domhandler@2.3.0, readable-stream@1.1.14)
├── jsdom@7.2.2 (acorn-globals@1.0.9, webidl-conversions@2.0.1, sax@1.2.1, abab@1.0.3, xml-name-validator@2.0.1, tough-cookie@2.2.2, symbol-tree@3.1.4, nwmatcher@1.3.8, cssom@0.3.1, parse5@1.5.1, whatwg-url-compat@0.6.5, acorn@2.7.0, escodegen@1.8.0, cssstyle@0.2.36, request@2.72.0)
└── lodash@4.13.1
dougwade npm-experiments/cannot-find-cheerio » ls -a node_modules/cheerio
.  ..  History.md  Readme.md  index.js	lib  node_modules  package.json
dougwade npm-experiments/cannot-find-cheerio » rm -r node_modules
dougwade npm-experiments/cannot-find-cheerio » npm config set registry http://npm.redfintest.com:4873/
dougwade npm-experiments/cannot-find-cheerio » npm i cheerio
npm WARN package.json cannot-find-cheerio@1.0.0 No description
npm WARN package.json cannot-find-cheerio@1.0.0 No repository field.
npm WARN package.json cannot-find-cheerio@1.0.0 No README data
cheerio@0.21.0 node_modules/cheerio
├── entities@1.1.1
├── dom-serializer@0.1.0 (domelementtype@1.1.3)
├── lodash.flatten@4.2.0 (lodash._baseflatten@4.2.1)
├── lodash.pick@4.2.1 (lodash._baseflatten@4.2.1, lodash.rest@4.0.3)
├── lodash.assignin@4.0.9 (lodash.keysin@4.1.4, lodash.rest@4.0.3)
├── lodash.bind@4.1.4 (lodash.rest@4.0.3, lodash._createwrapper@4.0.5)
├── lodash.merge@4.4.0 (lodash.isplainobject@4.0.4, lodash.rest@4.0.3, lodash.keysin@4.1.4, lodash._root@3.0.1, lodash._baseclone@4.5.7)
├── lodash.defaults@4.0.1 (lodash.rest@4.0.3, lodash.assigninwith@4.0.7)
├── css-select@1.2.0 (boolbase@1.0.0, css-what@2.1.0, nth-check@1.0.1, domutils@1.5.1)
├── htmlparser2@3.9.1 (domelementtype@1.3.0, inherits@2.0.1, domutils@1.5.1, domhandler@2.3.0, readable-stream@2.1.4)
├── lodash.filter@4.4.0 (lodash._basefilter@4.0.1, lodash._baseiteratee@4.7.0)
├── lodash.map@4.4.0 (lodash._baseeach@4.1.3, lodash._baseiteratee@4.7.0)
├── lodash.reject@4.4.0 (lodash._basefilter@4.0.1, lodash._baseiteratee@4.7.0)
├── lodash.foreach@4.3.0 (lodash._baseeach@4.1.3, lodash._baseiteratee@4.7.0)
├── lodash.reduce@4.4.0 (lodash._baseeach@4.1.3, lodash._basereduce@3.0.2, lodash._baseiteratee@4.7.0)
└── lodash.some@4.4.0 (lodash._baseeach@4.1.3, lodash._baseiteratee@4.7.0)
dougwade npm-experiments/cannot-find-cheerio » ls -a node_modules/cheerio
.  ..  History.md  Readme.md  lib  node_modules  package.json
```

closing

**Comment by doug-wade** [comment]
version 0.21 isn't even available on registry.npmjs.com; did you unpublish it?

```
dougwade npm-experiments/cannot-find-cheerio » npm config set registry https://registry.npmjs.org/
dougwade npm-experiments/cannot-find-cheerio » npm i cheerio@0.21.0
npm WARN package.json cannot-find-cheerio@1.0.0 No description
npm WARN package.json cannot-find-cheerio@1.0.0 No repository field.
npm WARN package.json cannot-find-cheerio@1.0.0 No README data
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i" "cheerio@0.21.0"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12

npm ERR! version not found: cheerio@0.21.0
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/doug.wade/npm-experiments/cannot-find-cheerio/npm-debug.log
```
