### ISSUE TITLE
Cannot read property parent of undefined

### ISSUE THREAD

**Issue by manishsingh10895** [cheeriojs/cheerio#932]
I am trying to load a local html file using **fs** and i was getting the same error, then I tried @davidbayo10 solution in one of the pull requests but still there's an error **cannot read property length of undefined** 
code for more info
```js 
    fs.readFile(p, (err, data)=> {
        HandleDataStructureResponse(err,{},data);
    });

 function HandleDataStructureResponse(err, res, body)
    {
        if(err) return console.log(err);
        let html = iconv.decode(body, 'ISO-8859-1');
        let $ = cheerio.load(body);
        var counter = 0;

        return [];
    }
```

Error log

```sh
<h1>Cannot read property 'length' of undefined</h1>
        <h2></h2>
        <pre>TypeError: Cannot read property 'length' of undefined
    at SBCSDecoder.write (/home/hp/Documents/Node/Geeky/node_modules/iconv-lite/encodings/sbcs-codec.js:61:32)
    at Object.decode (/home/hp/Documents/Node/Geeky/node_modules/iconv-lite/lib/index.js:38:23)
    at HandleDataStructureResponse (/home/hp/Documents/Node/Geeky/services/geekyParse.js:27:26)
    at Object.GetAllDataStructures (/home/hp/Documents/Node/Geeky/services/geekyParse.js:22:5)
    at /home/hp/Documents/Node/Geeky/routes/geeky.js:9:25
    at Layer.handle [as handle_request] (/home/hp/Documents/Node/Geeky/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/hp/Documents/Node/Geeky/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/hp/Documents/Node/Geeky/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/hp/Documents/Node/Geeky/node_modules/express/lib/router/layer.js:95:5)
    at /home/hp/Documents/Node/Geeky/node_modules/express/lib/router/index.js:277:22</pre>
```

**PS** I can log to console whole page using $.html()

**Comment by manishsingh10895** [comment]
Sorry, It was my fault, I was calling method twice, been stuck at this for few hours. Closing
