### ISSUE TITLE
ERROR in ./~/cheerio/package.json

### ISSUE THREAD

**Issue by ManuelDeLeon** [cheeriojs/cheerio#955]
I tried to use cheerio in my Angular 2 tests but I got this error:

```
    ERROR in ./~/cheerio/package.json
    Module parse failed: C:\MyFiles\Angular\App\node_modules\cheerio\package.json Unexpected token (2:9)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (2:9)
        at Parser.pp$4.raise (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp.unexpected (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:603:10)
        at Parser.pp.semicolon (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:581:61)
        at Parser.pp$1.parseExpressionStatement (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:966:10)
        at Parser.pp$1.parseStatement (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:730:24)
        at Parser.pp$1.parseBlock (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:981:25)
        at Parser.pp$1.parseStatement (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:709:33)
        at Parser.pp$1.parseTopLevel (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (C:\MyFiles\Angular\App\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (C:\MyFiles\Angular\App\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (C:\MyFiles\Angular\App\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (C:\MyFiles\Angular\App\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (C:\MyFiles\Angular\App\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at C:\MyFiles\Angular\App\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.provide (C:\MyFiles\Angular\App\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:52:20)
        at CachedInputFileSystem.readFile (C:\MyFiles\Angular\App\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:140:24)
     @ ./~/cheerio/index.js 11:18-43
```

I searched the issues and so I tried adding `.json` to webpack's resolve extensions but I get the same error.

Any suggestions?

**Comment by fb55** [comment]
You also need the `json` loader
