### ISSUE TITLE
Maximum call stack size exceeded, maybe a bug in  cheerio > css-select > domutils

### ISSUE THREAD

**Issue by Maslow** [cheeriojs/cheerio#991]
`cheerio` depends on `css-select`, which depends on `domutils`:

`
RangeError: Maximum call stack size exceeded
    at tag (.../node_modules/css-select/lib/general.js:21:11)
    at findAll (.../node_modules/domutils/lib/querying.js:87:6)
    at findAll (.../node_modules/domutils/lib/querying.js:90:27)
    at findAll (.../node_modules/domutils/lib/querying.js:90:27)
    at findAll (.../node_modules/domutils/lib/querying.js:90:27)
    at findAll (.../node_modules/domutils/lib/querying.js:90:27)
    at findAll (.../node_modules/domutils/lib/querying.js:90:27)
    at findAll (.../node_modules/domutils/lib/querying.js:90:27)
    at findAll (.../node_modules/domutils/lib/querying.js:90:27)
`

See also :
https://github.com/fb55/domutils/issues/19

**Comment by HackerCow** [comment]
Yes, this is a bug in `domutils`. There's [a PR](https://github.com/fb55/domutils/pull/22) that fixes the issue, as a workaround you can just use [the PR creator's fork](https://github.com/numeracy/domutils) instead of the original module.

**Comment by jugglinmike** [comment]
Looks like this issue is being tracked elsewhere.

**Comment by amit777** [comment]
hi, sorry to comment on closed ticket, but I see the bug in domutils has been fixed in 1.6.0+, however cheerio still installs 1.5.1.  Any plans on bumping up the domutils dependency?  I'm not sure if it has a major impact or not.
